modLoader = "javafml"
loaderVersion = "[45,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"

[[mods]]
modId = "aether_nitrogen"
version = "${file.jarVersion}"
displayName = "Nitrogen"
displayURL = "https://github.com/The-Aether-Team/Nitrogen"
authors = "bconlon"
description = '''
    A library used for the Aether series of mods.
    '''

[[dependencies.aether_nitrogen]]
    modId = "forge"
    mandatory = true
    versionRange = "[45.0.40,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_nitrogen]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.4]"
    ordering = "NONE"
    side = "BOTH"
