modLoader = "javafml"
loaderVersion = "[44,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"

[[mods]]
modId = "nitrogen"
version = "${file.jarVersion}"
displayName = "Nitrogen"
displayURL = "https://github.com/Gilded-Games/Nitrogen"
authors = "bconlon"
description = '''
    A library used for the Aether series of mods.
    '''

[[dependencies.nitrogen]]
    modId = "forge"
    mandatory = true
    versionRange = "[44.0.36,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.nitrogen]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.3]"
    ordering = "NONE"
    side = "BOTH"
