name: Trigger build

on: workflow_dispatch
  
jobs:
  trigger-build:
    if: ${{ github.event.label.name == 'status/build-approved' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - name: Trigger build
        env: 
          REMOTE_USER: ${{ github.event.pull_request.user.login }}
          REMOTE_URL: ${{ github.event.pull_request.head.repo.html_url }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
          REMOTE_BRANCH: ${{ format('{0}/{1}', github.event.pull_request.user.login, github.event.pull_request.head.ref) }}
          LOCAL_BRANCH: ${{ format('merge/{0}', github.event.pull_request.head.ref) }}
        run: |
            git config --local user.email "machine@gildedgames.com"
            git config --local user.name "Gilded-Games-Bot"
            git remote add ${REMOTE_USER} ${REMOTE_URL}
            git fetch ${REMOTE_USER}
            git checkout -B ${LOCAL_BRANCH} ${REMOTE_BRANCH}
            git merge ${REMOTE_BRANCH}
            git commit --allow-empty -m "chore: Trigger build"
            git push ${REMOTE_USER} HEAD:${BRANCH}
