name: Trigger build

on: 
  workflow_dispatch:
    inputs:
      remote_user:
        description: 'GitHub username of pull request creator'
        required: true
        default: 'Gilded-Games'
        type: string
      remote_name:
        description: 'GitHub name of the fork repository'
        required: true
        default: 'Nitrogen'
        type: string
      remote_branch:
        description: 'GitHub branch that the pull request is merging from'
        required: true
        default: '1.19'
        type: string
  
jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - name: Trigger build
        env: 
          REMOTE_USER: ${{ inputs.remote_user }}
          REMOTE_URL: ${{ format('git@github.com:{0}/{1}.git', inputs.remote_user, inputs.remote_name) }}
          BRANCH: ${{ inputs.remote_branch }}
          REMOTE_BRANCH: ${{ format('{0}/{1}', inputs.remote_user, inputs.remote_branch) }}
          LOCAL_BRANCH: ${{ format('merge/{0}', inputs.remote_branch) }}
        run: |
            git config --local user.email "machine@gildedgames.com"
            git config --local user.name "Gilded-Games-Bot"
            
            git remote add ${REMOTE_USER} ${REMOTE_URL}
            git fetch ${REMOTE_USER}
            git checkout -b ${LOCAL_BRANCH} ${REMOTE_BRANCH}
            git commit --allow-empty -m "chore: Trigger build"
            git push ${REMOTE_USER} HEAD:${BRANCH}
        
#            git merge ${REMOTE_BRANCH}
#            git checkout ${REMOTE_BRANCH}
#            git merge ${LOCAL_BRANCH}
#            git push ${REMOTE_USER} HEAD
