name: Trigger build

on:
  pull_request:
    types: [labeled]

jobs:
  track:
    if: ${{ github.event.label.name == 'status/build-approved' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: ${{ format('merge/', github.event.pull_request.head.repo.name) }}
