name: Trigger build

on:
  pull_request_review_comment
#    types: [created]

jobs:
#  check-user:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions-cool/check-user-permission@v2
#        id: checkUser
#        with:
#          require: 'write'
#          check-contributor: true
  trigger-build:
#    needs: check-user
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3
#        with:
#          repository: my-org/my-tools
#          path: my-tools
      - run: echo ${{ github.event.issue.pull_request.GITHUB_REF }}"
