name: Trigger build

on:
  pull_request:
    types: [labeled]

jobs:
  track:
    if: ${{ github.event.label.name == 'status/build-approved' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
            git config --local user.email "machine@gildedgames.com"
            git config --local user.name "Gilded-Games-Bot"
      - name: Merge master back to dev
        env: 
          REMOTE_USER: ${{ github.event.pull_request.user.login }}
          REMOTE_URL: ${{ github.event.pull_request.head.repo.html_url }}
          REMOTE_BRANCH: ${{ format('{0}/{1}', github.event.pull_request.user.login, github.event.pull_request.head.ref) }}
          LOCAL_BRANCH: ${{ format('merge/{0}', github.event.pull_request.head.ref) }}
        run: |
            git remote add ${REMOTE_USER} ${REMOTE_URL}
            git fetch ${REMOTE_USER}
            git checkout -B ${LOCAL_BRANCH} ${REMOTE_BRANCH}
            git merge ${REMOTE_BRANCH}
            git push --allow-empty -m "chore: Trigger build"
            
            
#        with:
#          repository: ${{ github.event.pull_request.head.repo.full_name }}
#          ref: 
#          path: 
