name: Trigger build

on:
  pull_request:
    types: [labeled]

jobs:
  check-user:
    if: ${{ github.event.label.name == 'status/build-approved' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@v2
        id: checkUser
        with:
          require: 'write'
          check-contributor: true
  trigger-build:
    needs: check-user
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3
#        with:
#          repository: my-org/my-tools
#          path: my-tools
      - run: echo "$GITHUB_REF"
      - run: echo "${{ github.event.pull_request }}"
      - run: echo "${{ github.event.pull_request.head }}"
      - run: echo "${{ github.event.pull_request.head.ref }}"
      - run: echo "${{ github.event.pull_request.repo }}"
      - run: echo "${{ github.event.pull_request.repo.name }}"
      - run: echo "${{ github.event.pull_request.base }}"
      - run: echo "${{ github.event.pull_request.base.ref }}"
