name: Trigger build

on:
  pull_request:
    types: [labeled]

jobs:
  track:
    if: ${{ github.event.label.name == 'status/build-approved' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
            git config --local user.email "machine@gildedgames.com"
            git config --local user.name "Gilded-Games-Bot"
      - name: Merge master back to dev
        run: |
            git fetch --unshallow
            git checkout -b merge/test
            git pull
            echo "${{ github.event.pull_request.head.repo.name }}"
            echo "${{ format('merge/', github.event.pull_request.head.repo.name) }}"
            git merge --no-ff ${{ github.event.pull_request.head.ref }}
            git push
            
            
#        with:
#          repository: ${{ github.event.pull_request.head.repo.full_name }}
#          ref: 
#          path: 
